{
 "title": "hw-monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS GET /api/a",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/a\",method=\"GET\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\",method=\"GET\",uri=\"/api/a\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LETENCY GET /api/a",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/a\"}[1m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  {
   "title": "RPS GET /api/b",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/api/b\",method=\"GET\"}[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5.*\",method=\"GET\",uri=\"/api/b\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LETENCY GET /api/b",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/b\"}[1m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/b\"}[1m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/b\"}[1m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/api/b\"}[1m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "Ingress Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPS"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "q=0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "q=0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "q=0.99"
    },
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "q=max"
    }
   ]
  },
  { "title": "k8s Metrics CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"otus-ms-hw-mn\", pod=~\"monitoring-deployment.*\"}[1m])) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORY USAGE (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"otus-ms-hw-mn\",pod=~\"monitoring-deployment.+\"}[1m])) by(pod) / 1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}