controller:
  kind: DaemonSet
  
  reportNodeInternalIp: true

  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: prometheus
      enabled: true

  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443

  service:
    type: NodePort